# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
internal_break_to_debugger <- function() {
    .Call('_CppDebugHelper_internal_break_to_debugger', PACKAGE = 'CppDebugHelper')
}

#' @export
debug_example_rcpp <- function() {
    .Call('_CppDebugHelper_debug_example_rcpp', PACKAGE = 'CppDebugHelper')
}

